### ISSUE TITLE
consider minimizing calls of 3rd party code especially for trivial functionality

### ISSUE THREAD

**Issue by alexanderlerch** [wkopacz6/BeatVox#3]
https://github.com/wkopacz6/BeatVox/blob/af1b39d0e69d669d6de0b30dc86b9a8f1e8d32ac/Python/venv1/OnsetDetection.py#L76

**Comment by wkopacz6** [comment]
Got rid of call for librosa.frames_to_time, might get rid of call to scipy.pick_peaks later
